version: '3'

services:
  web:
    build: .
    command: gunicorn skyeng_test.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      # параметры безопасности Django
      - "DJANGO_SECRET_KEY=django-insecure-@ti&43o8n6szb7l^v_$$eu*j(z1n6$$5##&@7g#@7)b_rqyukce#"
      - "DJANGO_DEBUG=False"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
      # postgres
#      - "DBNAME=postgres"
#      - "DBUSER=postgres"
#      - "DBPASSWORD=postgres"
#      - "DBHOST=db"
#      - "DBPORT=5432"
    restart: always
    networks:
      - djangonetwork
  db:
    image: sqlite
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5533:5432
    restart: always
    networks:
      - djangonetwork

volumes:
  postgres_data:

networks:
  djangonetwork:
    driver: bridge
